In [24]:
import pandas as pd
import pathlib

path = pathlib.Path('data').absolute()
inputFolder = path
df = pd.read_csv(path / 'Iris.csv')
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [25]:
X = df.drop(['Id', 'Species'], axis=1)
print(X.head())

y = df['Species']
print(y.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.25)

print(X_train.shape)
print(y_train.shape)


(112, 4)
(112,)


In [27]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9736842105263158

In [28]:
predictions = model.predict(X_test)
predictions[:10]

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor'],
      dtype=object)

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.9736842105263158
[[ 9  0  0]
 [ 0 16  0]
 [ 0  1 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.94      1.00      0.97        16
 Iris-virginica       1.00      0.92      0.96        13

       accuracy                           0.97        38
      macro avg       0.98      0.97      0.98        38
   weighted avg       0.98      0.97      0.97        38



In [30]:
import joblib as joblib

joblib.dump(model,'./output/randomforest_model.pkl')

['./output/randomforest_model.pkl']

In [31]:
import numpy as np

test_data = [5.1, 3.2, 1.5, 0.4]

test_data = np.array(test_data)
test_data = test_data.reshape(1, -1)
print(test_data)

[[5.1 3.2 1.5 0.4]]


In [32]:
test_data.shape

(1, 4)

In [33]:
# Load model

file = open('output/randomforest_model.pkl','rb')
trained_model = joblib.load(file)

In [34]:
prediction = trained_model.predict(test_data)
print(prediction)

['Iris-setosa']
